version: '3'
services:
  base: &base
    image: node:latest
    working_dir: /source
    volumes:
      - ./:/source
      - /source/node_modules
    command:
      - /bin/bash
      - -c
      - npm install

  dev:
    <<: *base
    container_name: portfolio_dev
    ports:
      - 8080:8080
    command:
      - /bin/bash
      - -c
      - npm install && npm run dev

  server:
    <<: *base
    container_name: portfolio_server
    ports:
      - 443:443
      - 80:80
    command:
      - /bin/bash
      - -c
      - npm install && npm start
